services:
  ai-app:
    build: .
    volumes:
      - ./:/app
    ports:
      - 8501:8501
    environment:
      - GOOGLE_API_KEY
      - TAVILY_API_KEY
      - LANGSMITH_API_KEY
      - LANGSMITH_TRACING
      - LANGSMITH_ENDPOINT
      - LANGSMITH_PROJECT
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/health"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s